"""widen price precision

Revision ID: 40d0c94de256
Revises: 36124be0a61c
Create Date: 2026-10-02 02:19:26.114426

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40d0c94de256"
down_revision: str | Sequence[str] | None = "36124be0a61c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_points",
        "price_eur_per_kwh",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        type_=sa.Numeric(precision=16, scale=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Lossy: PostgreSQL rounds existing prices to 6 decimals when narrowing the column.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_points",
        "price_eur_per_kwh",
        existing_type=sa.Numeric(precision=16, scale=10),
        type_=sa.NUMERIC(precision=10, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
